#!/bin/sh
#
# $Id: fscd 1943 2012-05-07 18:16:26Z bsdtrhodes $
#
# Start up for service monitoring daemon.
#

# PROVIDE: fscd
# REQUIRE: DAEMON syslogd
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="fscd"
rcvar="fscd_enable"
load_rc_config $name
: ${fscd_enable="NO"}

command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/usr/local/etc/$name.conf"

start_cmd=fscd_start

fscd_start()
{
	/usr/sbin/daemon -cf ${command} ${fscd_flags}
}

run_rc_command "$1"
