#!/bin/sh
#
# $Id: fscd 1943 2012-05-07 18:16:26Z bsdtrhodes $
#
# Start up for service monitoring daemon.
#

# PROVIDE: fscd
# REQUIRE: DAEMON syslogd
# BEFORE:  NETWORKING LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="fscd"
desc="FreeBSD Services Control Daemon"
rcvar="fscd_enable"
command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/usr/local/etc/$name.conf"

load_rc_config $name
: ${fscd_enable="NO"}
: ${fscd_flags=""}
command_args="-d"

run_rc_command "$1"
