#!/bin/sh
#
# $Id: fscd 1943 2012-05-07 18:16:26Z bsdtrhodes $
#
# Start up for service monitoring daemon.
#

# PROVIDE: fscd
# REQUIRE: DAEMON syslogd
# BEFORE:  NETWORKING LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="fscd"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
